{% set name = "rtree" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rtree-{{ version }}.tar.gz
  sha256: 9d97c7c5dcf25f6c0599c76d9933368c6a8d7238f2c1d00e76f1a69369ca82a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - pip
    - libspatialindex
  run:
    - python >={{ python_min }}
    - libspatialindex

test:
  imports:
    - rtree
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - numpy
  source_files:
    - tests/

about:
  summary: R-Tree spatial index for Python GIS
  home: https://github.com/Toblerity/rtree
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
    - mwtoews
