{% set version = "0.9.5" %}

package:
  name: rtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/Rtree/Rtree-{{ version }}.tar.gz
  sha256: 70387692061f8b5c45b1ae258fbd9a20b2f04b04af17af49545aeffaab443270

build:
  number: 0
  skip: true  # [win and vc<14]
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  host:
    - python
    - pip
    - libspatialindex
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree

about:
  home: http://toblerity.github.com/rtree/
  license: MIT
  license_file: LICENSE.txt
  summary: R-Tree spatial index for Python GIS

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
