{% set version = "1.2.0" %}

package:
  name: rtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/Rtree/Rtree-{{ version }}.tar.gz
  sha256: f5145f7852bf7f95c126fb16bf1a4c2ca9300ae151b07f8a0f7083ea47912675

build:
  number: 1
  skip: true  # [win and vc<14 or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libspatialindex
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree

about:
  home: https://github.com/Toblerity/rtree
  license: MIT
  license_file: LICENSE.txt
  summary: R-Tree spatial index for Python GIS

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
    - mwtoews
