{% set version = "1.3.0" %}

package:
  name: rtree
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/R/Rtree/rtree-{{ version }}.tar.gz
  sha256: b36e9dd2dc60ffe3d02e367242d2c26f7281b00e1aaf0c39590442edaaadd916

build:
  number: 3
  skip: true  # [win and vc<14 or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libspatialindex
    - setuptools
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree
  requires:
    - pytest
    - numpy
  source_files:
    - tests/

about:
  home: https://github.com/Toblerity/rtree
  license: MIT
  license_file: LICENSE.txt
  summary: R-Tree spatial index for Python GIS

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
    - mwtoews
