{% set version = "1.0.1" %}

package:
  name: rtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/Rtree/Rtree-{{ version }}.tar.gz
  sha256: 222121699c303a64065d849bf7038b1ecabc37b65c7fa340bedb38ef0e805429

build:
  number: 1
  skip: true  # [win and vc<14 or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libspatialindex
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree
  requires:
    - typing_extensions  # [py<38]

about:
  home: http://toblerity.github.com/rtree/
  license: MIT
  license_file: LICENSE.txt
  summary: R-Tree spatial index for Python GIS

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
