{% set version = "0.9.4" %}

package:
  name: rtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/R/Rtree/Rtree-{{ version }}.tar.gz
  sha256: cae327e2c03b3da4ea40d0fdf68f3e55fe9f302c56b9f31e1bfeb36dbea73f44

build:
  number: 2
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]

requirements:
  host:
    - python
    - pip
    - libspatialindex
  run:
    - python
    - libspatialindex

test:
  imports:
    - rtree

about:
  home: http://toblerity.github.com/rtree/
  license: MIT
  license_file: LICENSE.txt
  summary: 'R-Tree spatial index for Python GIS'

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
